/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.ruvents;

import org.junit.Test;
import static org.junit.Assert.*;

public class MapBuilderTest
{
    @Test public void testSomeLibraryMethod() {
        MapBuilder classUnderTest = new MapBuilder();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
