/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.ruvents;

import com.ruvents.components.builders.MapBuilder;
import org.junit.Assert;
import org.junit.Test;

public class MapBuilderTest
{
	@Test
	public void testPut() {
		var map01 = MapBuilder.create()
			.put("some", "value")
			.build();
		
		Assert.assertTrue(map01.containsKey("some"));
		
		var map02 = MapBuilder.create()
			.put("some", null)
			.build();
		
		Assert.assertTrue(map02.containsKey("some"));
		Assert.assertNull(map02.get("some"));
		
		var map03 = MapBuilder.create()
			.put("", "value")
			.build();
		
		Assert.assertTrue(map03.containsKey(""));
		Assert.assertEquals(map03.get(""), "value");
	}
	
	@Test(expected = IllegalArgumentException.class)
	public void testPutNullParameter() {
		MapBuilder.create()
			.put(null, "value1");
	}
}
